{
    "name": "Airesa",
    "summary": """
    Instance creator for airesa. This is the app.
    """,
    "author": "Diego Galvez, Vauxoo",
    "website": "https://www.vauxoo.com",
    "license": "OPL-1",
    "category": "Installer",
    "version": "19.0.1.0.12",
    "depends": [
        "accountant",
        "base_partner_sequence",
        "base_user_role",
        "credit_management",
        "crm",
        "generic_security_restriction",
        "hr",
        "l10n_mx_avoid_reversal_entry",
        "l10n_mx_edi_document",
        "l10n_mx_edi_payment_split",
        "point_of_sale",
        "product_pricelist_supplierinfo",
        "purchase_last_price_info",
        "purchase_order_supplierinfo_update",
        "sale_management",
        "stock_manual_transfer",
        "stock_no_negative",
    ],
    "data": [
        "data/res_company_data.xml",
        "data/res_partner_data.xml",
        "views/res_company_views.xml",
        "report/account_report.xml",
        "report/report_templates.xml",
        "report/report_invoice.xml",
    ],
    "demo": [
        "demo/crm_team_demo.xml",
        "demo/res_users_demo.xml",
        "demo/crm_team_member_demo.xml",
        "demo/generic_security_restriction_demo.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "airesa/static/src/scss/fonts.scss",
            "airesa/static/src/scss/report_invoice.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "application": True,
}
